# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/txia23/anaconda3/bin/cmake

# The command to remove a file.
RM = /home/txia23/anaconda3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/txia23/quantum/dma-image-processor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/txia23/quantum/dma-image-processor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/txia23/anaconda3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/home/txia23/anaconda3/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/txia23/anaconda3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/txia23/quantum/dma-image-processor/CMakeFiles /home/txia23/quantum/dma-image-processor//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/txia23/quantum/dma-image-processor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_spsc_ring

# Build rule for target.
test_spsc_ring: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_spsc_ring
.PHONY : test_spsc_ring

# fast build rule for target.
test_spsc_ring/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_spsc_ring.dir/build.make CMakeFiles/test_spsc_ring.dir/build
.PHONY : test_spsc_ring/fast

#=============================================================================
# Target rules for targets named test_slab_pool

# Build rule for target.
test_slab_pool: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_slab_pool
.PHONY : test_slab_pool

# fast build rule for target.
test_slab_pool/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_slab_pool.dir/build.make CMakeFiles/test_slab_pool.dir/build
.PHONY : test_slab_pool/fast

#=============================================================================
# Target rules for targets named test_processor

# Build rule for target.
test_processor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_processor
.PHONY : test_processor

# fast build rule for target.
test_processor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_processor.dir/build.make CMakeFiles/test_processor.dir/build
.PHONY : test_processor/fast

#=============================================================================
# Target rules for targets named test_dma_source

# Build rule for target.
test_dma_source: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_dma_source
.PHONY : test_dma_source

# fast build rule for target.
test_dma_source/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_dma_source.dir/build.make CMakeFiles/test_dma_source.dir/build
.PHONY : test_dma_source/fast

#=============================================================================
# Target rules for targets named test_archiver

# Build rule for target.
test_archiver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_archiver
.PHONY : test_archiver

# fast build rule for target.
test_archiver/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_archiver.dir/build.make CMakeFiles/test_archiver.dir/build
.PHONY : test_archiver/fast

#=============================================================================
# Target rules for targets named dma-image-processor

# Build rule for target.
dma-image-processor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dma-image-processor
.PHONY : dma-image-processor

# fast build rule for target.
dma-image-processor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dma-image-processor.dir/build.make CMakeFiles/dma-image-processor.dir/build
.PHONY : dma-image-processor/fast

#=============================================================================
# Target rules for targets named test_poisson

# Build rule for target.
test_poisson: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_poisson
.PHONY : test_poisson

# fast build rule for target.
test_poisson/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_poisson.dir/build.make CMakeFiles/test_poisson.dir/build
.PHONY : test_poisson/fast

#=============================================================================
# Target rules for targets named cnpy

# Build rule for target.
cnpy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cnpy
.PHONY : cnpy

# fast build rule for target.
cnpy/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnpy.dir/build.make CMakeFiles/cnpy.dir/build
.PHONY : cnpy/fast

_deps/cnpy-src/cnpy.o: _deps/cnpy-src/cnpy.cpp.o

.PHONY : _deps/cnpy-src/cnpy.o

# target to build an object file
_deps/cnpy-src/cnpy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnpy.dir/build.make CMakeFiles/cnpy.dir/_deps/cnpy-src/cnpy.cpp.o
.PHONY : _deps/cnpy-src/cnpy.cpp.o

_deps/cnpy-src/cnpy.i: _deps/cnpy-src/cnpy.cpp.i

.PHONY : _deps/cnpy-src/cnpy.i

# target to preprocess a source file
_deps/cnpy-src/cnpy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnpy.dir/build.make CMakeFiles/cnpy.dir/_deps/cnpy-src/cnpy.cpp.i
.PHONY : _deps/cnpy-src/cnpy.cpp.i

_deps/cnpy-src/cnpy.s: _deps/cnpy-src/cnpy.cpp.s

.PHONY : _deps/cnpy-src/cnpy.s

# target to generate assembly for a file
_deps/cnpy-src/cnpy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnpy.dir/build.make CMakeFiles/cnpy.dir/_deps/cnpy-src/cnpy.cpp.s
.PHONY : _deps/cnpy-src/cnpy.cpp.s

src/archiver.o: src/archiver.cpp.o

.PHONY : src/archiver.o

# target to build an object file
src/archiver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_archiver.dir/build.make CMakeFiles/test_archiver.dir/src/archiver.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dma-image-processor.dir/build.make CMakeFiles/dma-image-processor.dir/src/archiver.cpp.o
.PHONY : src/archiver.cpp.o

src/archiver.i: src/archiver.cpp.i

.PHONY : src/archiver.i

# target to preprocess a source file
src/archiver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_archiver.dir/build.make CMakeFiles/test_archiver.dir/src/archiver.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dma-image-processor.dir/build.make CMakeFiles/dma-image-processor.dir/src/archiver.cpp.i
.PHONY : src/archiver.cpp.i

src/archiver.s: src/archiver.cpp.s

.PHONY : src/archiver.s

# target to generate assembly for a file
src/archiver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_archiver.dir/build.make CMakeFiles/test_archiver.dir/src/archiver.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dma-image-processor.dir/build.make CMakeFiles/dma-image-processor.dir/src/archiver.cpp.s
.PHONY : src/archiver.cpp.s

src/config.o: src/config.cpp.o

.PHONY : src/config.o

# target to build an object file
src/config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dma-image-processor.dir/build.make CMakeFiles/dma-image-processor.dir/src/config.cpp.o
.PHONY : src/config.cpp.o

src/config.i: src/config.cpp.i

.PHONY : src/config.i

# target to preprocess a source file
src/config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dma-image-processor.dir/build.make CMakeFiles/dma-image-processor.dir/src/config.cpp.i
.PHONY : src/config.cpp.i

src/config.s: src/config.cpp.s

.PHONY : src/config.s

# target to generate assembly for a file
src/config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dma-image-processor.dir/build.make CMakeFiles/dma-image-processor.dir/src/config.cpp.s
.PHONY : src/config.cpp.s

src/dma_source.o: src/dma_source.cpp.o

.PHONY : src/dma_source.o

# target to build an object file
src/dma_source.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_dma_source.dir/build.make CMakeFiles/test_dma_source.dir/src/dma_source.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dma-image-processor.dir/build.make CMakeFiles/dma-image-processor.dir/src/dma_source.cpp.o
.PHONY : src/dma_source.cpp.o

src/dma_source.i: src/dma_source.cpp.i

.PHONY : src/dma_source.i

# target to preprocess a source file
src/dma_source.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_dma_source.dir/build.make CMakeFiles/test_dma_source.dir/src/dma_source.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dma-image-processor.dir/build.make CMakeFiles/dma-image-processor.dir/src/dma_source.cpp.i
.PHONY : src/dma_source.cpp.i

src/dma_source.s: src/dma_source.cpp.s

.PHONY : src/dma_source.s

# target to generate assembly for a file
src/dma_source.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_dma_source.dir/build.make CMakeFiles/test_dma_source.dir/src/dma_source.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dma-image-processor.dir/build.make CMakeFiles/dma-image-processor.dir/src/dma_source.cpp.s
.PHONY : src/dma_source.cpp.s

src/driver.o: src/driver.cpp.o

.PHONY : src/driver.o

# target to build an object file
src/driver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dma-image-processor.dir/build.make CMakeFiles/dma-image-processor.dir/src/driver.cpp.o
.PHONY : src/driver.cpp.o

src/driver.i: src/driver.cpp.i

.PHONY : src/driver.i

# target to preprocess a source file
src/driver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dma-image-processor.dir/build.make CMakeFiles/dma-image-processor.dir/src/driver.cpp.i
.PHONY : src/driver.cpp.i

src/driver.s: src/driver.cpp.s

.PHONY : src/driver.s

# target to generate assembly for a file
src/driver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dma-image-processor.dir/build.make CMakeFiles/dma-image-processor.dir/src/driver.cpp.s
.PHONY : src/driver.cpp.s

src/metrics.o: src/metrics.cpp.o

.PHONY : src/metrics.o

# target to build an object file
src/metrics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dma-image-processor.dir/build.make CMakeFiles/dma-image-processor.dir/src/metrics.cpp.o
.PHONY : src/metrics.cpp.o

src/metrics.i: src/metrics.cpp.i

.PHONY : src/metrics.i

# target to preprocess a source file
src/metrics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dma-image-processor.dir/build.make CMakeFiles/dma-image-processor.dir/src/metrics.cpp.i
.PHONY : src/metrics.cpp.i

src/metrics.s: src/metrics.cpp.s

.PHONY : src/metrics.s

# target to generate assembly for a file
src/metrics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dma-image-processor.dir/build.make CMakeFiles/dma-image-processor.dir/src/metrics.cpp.s
.PHONY : src/metrics.cpp.s

src/processor.o: src/processor.cpp.o

.PHONY : src/processor.o

# target to build an object file
src/processor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_processor.dir/build.make CMakeFiles/test_processor.dir/src/processor.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dma-image-processor.dir/build.make CMakeFiles/dma-image-processor.dir/src/processor.cpp.o
.PHONY : src/processor.cpp.o

src/processor.i: src/processor.cpp.i

.PHONY : src/processor.i

# target to preprocess a source file
src/processor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_processor.dir/build.make CMakeFiles/test_processor.dir/src/processor.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dma-image-processor.dir/build.make CMakeFiles/dma-image-processor.dir/src/processor.cpp.i
.PHONY : src/processor.cpp.i

src/processor.s: src/processor.cpp.s

.PHONY : src/processor.s

# target to generate assembly for a file
src/processor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_processor.dir/build.make CMakeFiles/test_processor.dir/src/processor.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dma-image-processor.dir/build.make CMakeFiles/dma-image-processor.dir/src/processor.cpp.s
.PHONY : src/processor.cpp.s

tests/test_archiver.o: tests/test_archiver.cpp.o

.PHONY : tests/test_archiver.o

# target to build an object file
tests/test_archiver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_archiver.dir/build.make CMakeFiles/test_archiver.dir/tests/test_archiver.cpp.o
.PHONY : tests/test_archiver.cpp.o

tests/test_archiver.i: tests/test_archiver.cpp.i

.PHONY : tests/test_archiver.i

# target to preprocess a source file
tests/test_archiver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_archiver.dir/build.make CMakeFiles/test_archiver.dir/tests/test_archiver.cpp.i
.PHONY : tests/test_archiver.cpp.i

tests/test_archiver.s: tests/test_archiver.cpp.s

.PHONY : tests/test_archiver.s

# target to generate assembly for a file
tests/test_archiver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_archiver.dir/build.make CMakeFiles/test_archiver.dir/tests/test_archiver.cpp.s
.PHONY : tests/test_archiver.cpp.s

tests/test_dma_source.o: tests/test_dma_source.cpp.o

.PHONY : tests/test_dma_source.o

# target to build an object file
tests/test_dma_source.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_dma_source.dir/build.make CMakeFiles/test_dma_source.dir/tests/test_dma_source.cpp.o
.PHONY : tests/test_dma_source.cpp.o

tests/test_dma_source.i: tests/test_dma_source.cpp.i

.PHONY : tests/test_dma_source.i

# target to preprocess a source file
tests/test_dma_source.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_dma_source.dir/build.make CMakeFiles/test_dma_source.dir/tests/test_dma_source.cpp.i
.PHONY : tests/test_dma_source.cpp.i

tests/test_dma_source.s: tests/test_dma_source.cpp.s

.PHONY : tests/test_dma_source.s

# target to generate assembly for a file
tests/test_dma_source.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_dma_source.dir/build.make CMakeFiles/test_dma_source.dir/tests/test_dma_source.cpp.s
.PHONY : tests/test_dma_source.cpp.s

tests/test_poisson.o: tests/test_poisson.cpp.o

.PHONY : tests/test_poisson.o

# target to build an object file
tests/test_poisson.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_poisson.dir/build.make CMakeFiles/test_poisson.dir/tests/test_poisson.cpp.o
.PHONY : tests/test_poisson.cpp.o

tests/test_poisson.i: tests/test_poisson.cpp.i

.PHONY : tests/test_poisson.i

# target to preprocess a source file
tests/test_poisson.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_poisson.dir/build.make CMakeFiles/test_poisson.dir/tests/test_poisson.cpp.i
.PHONY : tests/test_poisson.cpp.i

tests/test_poisson.s: tests/test_poisson.cpp.s

.PHONY : tests/test_poisson.s

# target to generate assembly for a file
tests/test_poisson.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_poisson.dir/build.make CMakeFiles/test_poisson.dir/tests/test_poisson.cpp.s
.PHONY : tests/test_poisson.cpp.s

tests/test_processor.o: tests/test_processor.cpp.o

.PHONY : tests/test_processor.o

# target to build an object file
tests/test_processor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_processor.dir/build.make CMakeFiles/test_processor.dir/tests/test_processor.cpp.o
.PHONY : tests/test_processor.cpp.o

tests/test_processor.i: tests/test_processor.cpp.i

.PHONY : tests/test_processor.i

# target to preprocess a source file
tests/test_processor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_processor.dir/build.make CMakeFiles/test_processor.dir/tests/test_processor.cpp.i
.PHONY : tests/test_processor.cpp.i

tests/test_processor.s: tests/test_processor.cpp.s

.PHONY : tests/test_processor.s

# target to generate assembly for a file
tests/test_processor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_processor.dir/build.make CMakeFiles/test_processor.dir/tests/test_processor.cpp.s
.PHONY : tests/test_processor.cpp.s

tests/test_slab_pool.o: tests/test_slab_pool.cpp.o

.PHONY : tests/test_slab_pool.o

# target to build an object file
tests/test_slab_pool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_slab_pool.dir/build.make CMakeFiles/test_slab_pool.dir/tests/test_slab_pool.cpp.o
.PHONY : tests/test_slab_pool.cpp.o

tests/test_slab_pool.i: tests/test_slab_pool.cpp.i

.PHONY : tests/test_slab_pool.i

# target to preprocess a source file
tests/test_slab_pool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_slab_pool.dir/build.make CMakeFiles/test_slab_pool.dir/tests/test_slab_pool.cpp.i
.PHONY : tests/test_slab_pool.cpp.i

tests/test_slab_pool.s: tests/test_slab_pool.cpp.s

.PHONY : tests/test_slab_pool.s

# target to generate assembly for a file
tests/test_slab_pool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_slab_pool.dir/build.make CMakeFiles/test_slab_pool.dir/tests/test_slab_pool.cpp.s
.PHONY : tests/test_slab_pool.cpp.s

tests/test_spsc_ring.o: tests/test_spsc_ring.cpp.o

.PHONY : tests/test_spsc_ring.o

# target to build an object file
tests/test_spsc_ring.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_spsc_ring.dir/build.make CMakeFiles/test_spsc_ring.dir/tests/test_spsc_ring.cpp.o
.PHONY : tests/test_spsc_ring.cpp.o

tests/test_spsc_ring.i: tests/test_spsc_ring.cpp.i

.PHONY : tests/test_spsc_ring.i

# target to preprocess a source file
tests/test_spsc_ring.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_spsc_ring.dir/build.make CMakeFiles/test_spsc_ring.dir/tests/test_spsc_ring.cpp.i
.PHONY : tests/test_spsc_ring.cpp.i

tests/test_spsc_ring.s: tests/test_spsc_ring.cpp.s

.PHONY : tests/test_spsc_ring.s

# target to generate assembly for a file
tests/test_spsc_ring.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_spsc_ring.dir/build.make CMakeFiles/test_spsc_ring.dir/tests/test_spsc_ring.cpp.s
.PHONY : tests/test_spsc_ring.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... cnpy"
	@echo "... dma-image-processor"
	@echo "... test_archiver"
	@echo "... test_dma_source"
	@echo "... test_poisson"
	@echo "... test_processor"
	@echo "... test_slab_pool"
	@echo "... test_spsc_ring"
	@echo "... _deps/cnpy-src/cnpy.o"
	@echo "... _deps/cnpy-src/cnpy.i"
	@echo "... _deps/cnpy-src/cnpy.s"
	@echo "... src/archiver.o"
	@echo "... src/archiver.i"
	@echo "... src/archiver.s"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/dma_source.o"
	@echo "... src/dma_source.i"
	@echo "... src/dma_source.s"
	@echo "... src/driver.o"
	@echo "... src/driver.i"
	@echo "... src/driver.s"
	@echo "... src/metrics.o"
	@echo "... src/metrics.i"
	@echo "... src/metrics.s"
	@echo "... src/processor.o"
	@echo "... src/processor.i"
	@echo "... src/processor.s"
	@echo "... tests/test_archiver.o"
	@echo "... tests/test_archiver.i"
	@echo "... tests/test_archiver.s"
	@echo "... tests/test_dma_source.o"
	@echo "... tests/test_dma_source.i"
	@echo "... tests/test_dma_source.s"
	@echo "... tests/test_poisson.o"
	@echo "... tests/test_poisson.i"
	@echo "... tests/test_poisson.s"
	@echo "... tests/test_processor.o"
	@echo "... tests/test_processor.i"
	@echo "... tests/test_processor.s"
	@echo "... tests/test_slab_pool.o"
	@echo "... tests/test_slab_pool.i"
	@echo "... tests/test_slab_pool.s"
	@echo "... tests/test_spsc_ring.o"
	@echo "... tests/test_spsc_ring.i"
	@echo "... tests/test_spsc_ring.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

